apiVersion: apps/v1 
kind: Deployment
metadata:
  name: fe-deployment
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 5
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: myregistrydomain.com/chenchuk77/frontend:2.9-SNAPSHOT
        ports:
        - containerPort: 8080

