apiVersion: apps/v1 
kind: Deployment
metadata:
  name: fe-deployment
spec:
  selector:
    matchLabels:
      app: fe
  replicas: 4
  template:
    metadata:
      labels:
        app: fe
    spec:
      containers:
      - name: fe
        image: myregistrydomain.com/chenchuk77/frontend:2.7-SNAPSHOT
        ports:
        - containerPort: 8080

