apiVersion: apps/v1 
kind: Deployment
metadata:
  name: be-deployment
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: myregistrydomain.com/chenchuk77/backend:3.3-SNAPSHOT
        ports:
        - containerPort: 8085

